//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CREA.Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Building()
        {
            this.Properties = new HashSet<Property>();
        }
    
        public int BuildingID { get; set; }
        public Nullable<int> BathroomTotal { get; set; }
        public Nullable<int> BedroomsTotal { get; set; }
        public string CoolingType { get; set; }
        public Nullable<bool> FireplacePresent { get; set; }
        public string HeatingFuel { get; set; }
        public string HeatingType { get; set; }
        public string SizeInterior { get; set; }
        public string Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Property> Properties { get; set; }
    }
}
