//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CREA.Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.Photos = new HashSet<Photo>();
            this.PropertyAgents = new HashSet<PropertyAgent>();
        }
    
        public int PropertyID { get; set; }
        public Nullable<int> PropertyDetailsID { get; set; }
        public string ListingID { get; set; }
        public string Board { get; set; }
        public string Business { get; set; }
        public Nullable<int> BuildingID { get; set; }
        public Nullable<int> LandID { get; set; }
        public string StreatAddress { get; set; }
        public string AddressLine1 { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Features { get; set; }
        public string FarmType { get; set; }
        public string OwnershipType { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string PropertyType { get; set; }
        public string PublicRemarks { get; set; }
        public string TransactionType { get; set; }
        public string UtilitiesAvailable { get; set; }
        public string ViewType { get; set; }
        public string WaterFrontType { get; set; }
        public string AnalyticsClick { get; set; }
        public string AnalyticsView { get; set; }
        public string MoreInformationLink { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual Land Land { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photo> Photos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyAgent> PropertyAgents { get; set; }
    }
}
