//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CREA.Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyAgent
    {
        public int PropertyAgentID { get; set; }
        public int PropertyID { get; set; }
        public Nullable<int> AgentID { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Property Property { get; set; }
    }
}
